# name1: ci/cd
on: 
  pull_request:
    branches:
      - main
      - master
  push:
    branches: 
      - main 
      - master
      
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
   
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
          channel: 'any'
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
       # !! This is for android only 
      - run: flutter build apk 
      - run: flutter build appbundle
        # !! This is for web only 
      - run: flutter build web
         # !! This is for ios only 
      - run: flutter build ios --release --no-codesign

        name: 'test'
      - run: flutter --version
      #!! to create release for your source code   
      #!! in order to do this folllow this youtube tutorials 
      #!! https://www.youtube.com/watch?v=9L7OfshBqX8&t=489s
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/apk/debug/*"
         tag: v1.0.${{ github.run_number }} 
         token: ${{ secrets.TOKEN }}
